services:
  - type: web
    name: safestreet-backend
    env: python
    buildCommand: docker build -t safestreet-backend .
    startCommand: gunicorn app:app --bind 0.0.0.0:5000 --workers 1 --timeout 120
    envVars:
      - key: MONGODB_URI
        fromService: safestreet-mongodb
    ports:
      - port: 5000
    healthCheckPath: /health
    autoDeploy: true
    memory: 8192
    cpu: 2
    disk: 10240
    
databases:
  - type: mongodb
    name: safestreet-mongodb
